### ISSUE TITLE
Breaks scheduled publishing on 8.6.2

### ISSUE THREAD

**Issue by nzdev** [christophermuya/ContentProtector#2]
Hi, 

Having this package installed breaks scheduled publishing on v8.6.2 even if publishing is not restricted

System.NullReferenceException: Object reference not set to an instance of an object.
   at ContentProtector.App_Plugins.ContentProtector.Components.ActionBlocker.ContentService_Saving(IContentService sender, ContentSavingEventArgs eventArgs)
   at Umbraco.Core.Events.TypedEventHandler`2.Invoke(TSender sender, TEventArgs e)
   at Umbraco.Core.Events.QueuingEventDispatcherBase.DispatchCancelable[TSender,TArgs](TypedEventHandler`2 eventHandler, TSender sender, TArgs args, String eventName) in D:\a\1\s\src\Umbraco.Core\Events\QueuingEventDispatcherBase.cs:line 54
   at Umbraco.Core.Services.Implement.ContentService.SaveAndPublish(IContent content, String culture, Int32 userId, Boolean raiseEvents) in D:\a\1\s\src\Umbraco.Core\Services\Implement\ContentService.cs:line 890
   at Umbraco.Core.Services.Implement.ContentService.<PerformScheduledPublishInternal>d__59.MoveNext() in D:\a\1\s\src\Umbraco.Core\Services\Implement\ContentService.cs:line 1434
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Umbraco.Core.Services.Implement.ContentService.PerformScheduledPublish(DateTime date) in D:\a\1\s\src\Umbraco.Core\Services\Implement\ContentService.cs:line 1363
   at Umbraco.Web.Scheduling.ScheduledPublishing.PerformRun() in D:\a\1\s\src\Umbraco.Web\Scheduling\ScheduledPublishing.cs:line 72

**Comment by malkag** [comment]
Got the same exception when trying to SaveAndPublish node programmatically (when Backoffice user is NOT logged-in)
v 8.9.1
